"""Product Foundation library contracts for safe version/history context."""

from .contracts import (
    BranchConflictError,
    BranchPreview,
    ConfirmationRequiredError,
    ContextState,
    CURRENT_POINTER_SCHEMA,
    DownloadArtifact,
    InvalidContextError,
    NonHeadWriteError,
    PersistenceError,
    ProductFoundationError,
    ReadOnlyVersionError,
    SnapshotInvalidError,
    StaleRevisionError,
    UndoPreview,
    UndoTargetError,
    UndoUnavailableError,
    VersionComparison,
    VersionNode,
    VersionNotFoundError,
    VersionView,
    VERSION_CONTEXT_SCHEMA,
)
from .service import VersionContext
from .workspace_model import (
    WorkspaceDefinition,
    WorkspaceModel,
    WorkspaceVersionContext,
    default_workspace_model,
)

__all__ = [
    "BranchConflictError",
    "BranchPreview",
    "ConfirmationRequiredError",
    "ContextState",
    "CURRENT_POINTER_SCHEMA",
    "DownloadArtifact",
    "InvalidContextError",
    "NonHeadWriteError",
    "PersistenceError",
    "ProductFoundationError",
    "ReadOnlyVersionError",
    "SnapshotInvalidError",
    "StaleRevisionError",
    "UndoPreview",
    "UndoTargetError",
    "UndoUnavailableError",
    "VersionComparison",
    "VersionContext",
    "VersionNode",
    "VersionNotFoundError",
    "VersionView",
    "VERSION_CONTEXT_SCHEMA",
    "WorkspaceDefinition",
    "WorkspaceModel",
    "WorkspaceVersionContext",
    "default_workspace_model",
]
